DEBUG:
  eval_in_train: 1
  eval_in_train_per_iter: -1
INPUT:
  CLASSES: ['background', 'wall']
  #SCENES: ['0058113bdc8bee5f387bb5ad316d7b28', '00922f91aa09dbdda3a74489ea0e21eb']
MODEL:
  ROI__ONLY: False
  LOSS:
    WEIGHTS: [4.0,4,2,2,  0, 1, 1]
SOLVER:
  EPOCHS: 20
  EPOCHS_BETWEEN_TEST: 5
  IMS_PER_BATCH: 1
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.000
  LR_STEP_EPOCHS: (10,)
  CHECKPOINT_PERIOD_EPOCHS: 2
  WARMUP_EPOCHS: 0.1
  TRACK_RUNNING_STATS: False
OUTPUT_DIR: "RES/res_wall_Fpn4321_bs1_lr5"
TEST:
  IMS_PER_BATCH: 1
  IOU_THRESHOLD: 0.3
